### ISSUE TITLE
Refactoring:メソッドの抽出

### ISSUE THREAD

**Issue by deris** [akechi/todobot#13]
issues消化するにしてもある程度Refactoringしてからじゃないと厳しげ。
せめて機能ごとにメソッド分けくらいは

**Comment by bgnori** [comment]
つーか、DBまわりも含めてそれなりに書き直さないと。
FrameWork移行のsubitemといったところですかねぇ。

**Comment by bgnori** [comment]
とりあえずのレベルでは実行した。

https://github.com/akechi/todobot/commit/96bba3d603f66ef8b13ae3c5899778613622fbfd

ただテストができてないんだよなー
