### ISSUE TITLE
list時に絞り込み検索がしたい

### ISSUE THREAD

**Issue by supermomonga** [akechi/todobot#19]
list系コマンドで絞込みがしたい。
例）
`#todo list <keyword>`
`#todo listof <userid> <keyword>`
こんなかんじ？

**Comment by bgnori** [comment]
tag付けとかもありえそうだ。 => "#"を使ってもらうでいいような。
複数キーワードがほしいのだろうか。=> ' #todo list <keyword1> <keyword2> ...
pageで量を制限したいとかもあったなぁ。=> #1 キーワードに数字始まり無しだと思っておけばいいか？

**Comment by supermomonga** [comment]
私の場合はタグ検索でも十分です。

> 複数キーワードがほしいのだろうか。=> ' #todo list ...

私は単数で十分だなぁ

> pageで量を制限したいとかもあったなぁ。

あーそっか、数字だと記法がぶつかるのか…

**Comment by bgnori** [comment]
https://github.com/akechi/todobot/compare/ea996bef876e...b7e14cee7c0f
その他いろいろ。
