### ISSUE TITLE
日付・時刻フォーマットの統一

### ISSUE THREAD

**Issue by supermomonga** [akechi/todobot#20]
addした時のメッセージで、時刻にミリ秒？が含まれている。

```
[_] 0252 supermomonga 2013-06-28 13:02:03.910459 [ruby] Fiber Chat のソースコード読む https://gist.github.com/pfleidi/835268
```

list時のメッセージでは含まれていない

```
[_] 0053 bgnori 2013-05-16 20:48:14 isokaze再起動後のユーザプロセス起動について検討
[_] 0142 bgnori 2013-05-30 16:00:48 /last-loginを作る
```

ので、日付・時刻表記を統一したいです。

**Comment by bgnori** [comment]
内部的にdatetimeを使っているせいですね。前はsqliteのdatetimeだったので。
prnformatを書き換えれば良さそう。ただdumpとのかねあいに注意、か。

**Comment by bgnori** [comment]
３文字で統一すればガタガタしなさそう

・さっき

・むかし

・うーん

・いつか

どーするねん・・・

**Comment by supermomonga** [comment]
３文字はNETAですのでMUSHIしてOK

**Comment by supermomonga** [comment]
n日前、に+1

**Comment by bgnori** [comment]
https://github.com/akechi/todobot/compare/4a85946db9a0...86d13d9bef01
で対応
