### ISSUE TITLE
add「#todo addto [user1,user2,user3...] task_description」syntax

### ISSUE THREAD

**Issue by deris** [akechi/todobot#8]

**Comment by bgnori** [comment]
https://github.com/akechi/todobot/compare/2645abba4192...0ef3161ef588
https://github.com/akechi/todobot/compare/0ef3161ef588...3a81be637461
https://github.com/akechi/todobot/compare/3a81be637461...4d58d4703018
https://github.com/akechi/todobot/compare/4d58d4703018...3789c991cc6a
